language: node_js
node_js:
  - 12

services:
  - docker
script:
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user otejada/udagram-api-user:v2
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed otejada/udagram-api-feed:v2
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag reverseproxy otejada/reverseproxy:v2
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend otejada/udagram-frontend:v2

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push otejada/udagram-api-feed:v2
  - docker push otejada/udagram-api-user:v2
  - docker push otejada/reverseproxy:v2
  - docker push otejada/udagram-frontend:v2


