apiVersion: v1
kind: Service
metadata:
  labels:
    app: udagram-api-feed
  name: udagram-api-feed
  namespace: default
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: udagram-api-feed
  sessionAffinity: None
status:
  loadBalancer: {}
